# @MajoraGenerator({"register_doctrine_em": {"em": "default"}})
# @MajoraGenerator({"register_doctrine_em": {"prefix": "Gesco\\Si\\Component\\MajoraNamespace\\Entity"}})
# @MajoraGenerator({"register_doctrine_em": {"bundle": "GescoSiMajoraNamespaceBundle"}})
# @MajoraGenerator({"register_doctrine_em": {"alias": "GescoSiMajoraNamespace"}})

Gesco\Si\Component\MajoraNamespace\Entity\MajoraEntity:
    type: entity
    repositoryClass: Gesco\Si\Component\MajoraNamespace\Repository\Doctrine\MajoraEntityDoctrineRepository
    table: gesco_si_majora_entity
    actAs:
        Timestampable: ~
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:

        # your other MajoraEntity properties here

        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update

    #manyToOne:
    #    example:
    #        targetEntity: Example
    #        inversedBy: majoraEntitys
    #        joinColumn:
    #            name: example_id
    #            referencedColumnName: id

    #oneToMany:
    #    examples:
    #        targetEntity: Example
    #        mappedBy: majoraEntity
    #        cascade: ['persist', 'remove']

    #manyToMany:
    #    examples:
    #        targetEntity: Example
    #        joinTable:
    #            name: gesco_majora_entity_example
    #            joinColumns:
    #                majora_entity_id:
    #                    referencedColumnName: id
    #            inverseJoinColumns:
    #                example_id:
    #                    referencedColumnName: id
