# @MajoraGenerator({"include_routing": {"target": "/config/routing/routing_admin.yml"}})
# @MajoraGenerator({"include_routing": {"route": "gesco_admin_majora_namespace"}})
# @MajoraGenerator({"include_routing": {"resource": "@GescoAdminMajoraNamespaceBundle/Resources/config/routing.yml"}})
